<?php

namespace Database\Seeders;

use App\Models\CfgUserCal;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CfgUserCalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fkidgestorparam = env('GESTOR', '1');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        CfgUserCal::truncate();
        
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 28, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 70, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 17, 'uctipo' => 1, 'ucregporpagina' => 300, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 40, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 52, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 85, 'ucheight' => 80, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 19, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 51, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 15, 'uctipo' => 1, 'ucregporpagina' => 3, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 16, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 43, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 29, 'uctipo' => 1, 'ucregporpagina' => 6, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 100, 'ucheight' => 100, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 20, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 54, 'uctipo' => 1, 'ucregporpagina' => 50, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 9, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 55, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 56, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 100, 'ucheight' => 100, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 57, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 58, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 59, 'uctipo' => 1, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 59, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 85, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 62, 'uctipo' => 1, 'ucregporpagina' => 7, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 69, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 70, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 124, 'uctipo' => 1, 'ucregporpagina' => 15, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 135, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 140, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1'); 
    }
}
