<?php

namespace Database\Seeders;

use App\Models\CfgUserCal;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CfgUserCalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fkidgestorparam = env('GESTOR', '1');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        CfgUserCal::truncate();
        CfgUserCal::create([ 'ucoptsearch' => '[cbxBuscasSalvasA:5,, tfNumeroLei:2,, cbxLegislatura:3,]', 'fkidusuario' => 1, 'fkidcal' => 1, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 85, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 2, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 85, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 1, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 51, 'ucheight' => 50, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 3, 'uctipo' => 2, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 70, 'ucheight' => 60, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 5, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 85, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 5, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 10, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 10, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 37, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 70, 'ucheight' => 60, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 11, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 70, 'ucheight' => 60, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 7, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 80, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 7, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 75, 'ucheight' => 85, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 12, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 80, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 12, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 75, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 6, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 80, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 6, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 75, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 14, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 0, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 85, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 14, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 0, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 38, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 0, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 85, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 38, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 0, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 39, 'uctipo' => 1, 'ucregporpagina' => 1, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 0, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 85, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 28, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 70, 'ucheight' => 90, 'ucuseteclaatalho' => 0, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 17, 'uctipo' => 1, 'ucregporpagina' => 300, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 41, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 47, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 40, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 52, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 85, 'ucheight' => 80, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 18, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 19, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 51, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 15, 'uctipo' => 1, 'ucregporpagina' => 3, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 44, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 35, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 32, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 50, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 30, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 16, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 43, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 45, 'uctipo' => 1, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 46, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 48, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 31, 'uctipo' => 1, 'ucregporpagina' => 25, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 49, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 29, 'uctipo' => 1, 'ucregporpagina' => 6, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 100, 'ucheight' => 100, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 20, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 53, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 33, 'uctipo' => 1, 'ucregporpagina' => 2, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 54, 'uctipo' => 1, 'ucregporpagina' => 50, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 9, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 55, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 56, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 100, 'ucheight' => 100, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 57, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 58, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 59, 'uctipo' => 1, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 75, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 60, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 85, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 59, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 80, 'ucheight' => 85, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 61, 'uctipo' => 2, 'ucregporpagina' => 1, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 60, 'ucheight' => 40, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 62, 'uctipo' => 1, 'ucregporpagina' => 7, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 90, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 63, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 1, 'ucsavefavorito' => 1, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 95, 'ucheight' => 90, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 69, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 70, 'uctipo' => 1, 'ucregporpagina' => 5, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 85, 'uctipo' => 1, 'ucregporpagina' => 3, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 130, 'uctipo' => 1, 'ucregporpagina' => 2, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 124, 'uctipo' => 1, 'ucregporpagina' => 15, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 125, 'uctipo' => 1, 'ucregporpagina' => 9, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 135, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 136, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 138, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        CfgUserCal::create([ 'ucoptsearch' => '', 'fkidusuario' => 1, 'fkidcal' => 140, 'uctipo' => 1, 'ucregporpagina' => 10, 'ucusefavorito' => 0, 'ucsavefavorito' => 0, 'ucusesizecolumnsrelative' => 1, 'ucmaximizado' => 0, 'ucsizefixo' => 0, 'ucsizerelative' => 1, 'ucwidth' => 0, 'ucheight' => 0, 'ucuseteclaatalho' => 1, 'ucstatus' => 1, 'ucversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flaguser' => 0]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1'); 
    }
}
