<?php

namespace Database\Seeders;

use App\Models\ColumnCal;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ColumnCalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fkidgestorparam = env('GESTOR', '1');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        ColumnCal::truncate();

        ColumnCal::create(["fkidcal" => 8, "clsize" => "15", "clheader" => "Identificação", "clname" => "numerogerado", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 8, "clsize" => "35", "clheader" => "Conteúdo", "clname" => "conteudo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 8, "clsize" => "20", "clheader" => "Dados", "clname" => "datacadastro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 8, 'clsize' => '10', 'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 16, 'clorder' => 200, 'clvisible' => 1, 'clstatus' => 1, 'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
    

        ColumnCal::create(["fkidcal" => 9, "clsize" => "15", "clheader" => "Identificação", "clname" => "anumerogerado", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 9, "clsize" => "35", "clheader" => "Conteúdo", "clname" => "aconteudo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 9, "clsize" => "20", "clheader" => "Dados", "clname" => "adatacadastro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 9, 'clsize' => '10', 'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 16, 'clorder' => 200, 'clvisible' => 1, 'clstatus' => 1, 'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        ColumnCal::create(["fkidcal" => 15, "clsize" => "30", "clheader" => "Identificação", "clname" => "clscidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 9, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 15, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 16, "clsize" => "10", "clheader" => "Status", "clname" => "cgstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 16, 'clsize' => '10', 'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 13, 'clorder' => 50, 'clvisible' => 1, 'clstatus' => 1, 'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 16, "clsize" => "50", "clheader" => "Identificação", "clname" => "cgidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 17, "clsize" => "15", "clheader" => "Estado", "clname" => "estado", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 17, "clsize" => "30", "clheader" => "Identificação", "clname" => "cdidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 17, "clsize" => "5", "clheader" => "Cód", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 9, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 17, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 19, "clsize" => "30", "clheader" => "Identificação", "clname" => "pdidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 9, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "2", "clheader" => "Código", "clname" => "pdcodigo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "10", "clheader" => "Responsável", "clname" => "unidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 13, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "5", "clheader" => "E-mail", "clname" => "pdemail", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "5", "clheader" => "Fone", "clname" => "pdfone", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 17, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "10", "clheader" => "Competência", "clname" => "pdcompetencia", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 18, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "10", "clheader" => "Endereço", "clname" => "pdendereco", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "10", "clheader" => "Dep. Nível Acima", "clname" => "fkiddivisaonivelacima", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "10", "clheader" => "Unidade Pertencente", "clname" => "fkidunidade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 19, "clsize" => "2", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 80, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        ColumnCal::create(["fkidcal" => 20, "clsize" => "15", "clheader" => "Identificação", "clname" => "ecidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 20, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        
        ColumnCal::create(["fkidcal" => 21, "clsize" => "20", "clheader" => "Funcionário", "clname" => "fkidunico", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 21, "clsize" => "20", "clheader" => "Unidade", "clname" => "fkidunidade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 21, "clsize" => "20", "clheader" => "Dados", "clname" => "fcmatricula", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 40, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 21, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 80, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Usuário", "clname" => "nomeMembro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Grupo", "clname" => "gidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 22, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Status", "clname" => "ustatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Login", "clname" => "ulogin", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Obs.", "clname" => "uanotation", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 22, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "Data", "clname" => "uversao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 22, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 22, "clsize" => "15", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 18, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
  
        ColumnCal::create(["fkidcal" => 28, "clsize" => "0.2", "clheader" => "Status", "clname" => "clstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 22, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "2", "clheader" => "Tipo", "clname" => "cltipo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "2", "clheader" => "Base", "clname" => "clbase", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 27, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "2", "clheader" => "Obs", "clname" => "clobserve", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "50", "clheader" => "Identificação", "clname" => "clidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "15", "clheader" => "Data", "clname" => "clversao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "7", "clheader" => "Cód", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 5, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "2", "clheader" => "Rota", "clname" => "clrota", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 28, "clsize" => "0.5", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 29, "clsize" => "15", "clheader" => "Identificação", "clname" => "tidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 11, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 29, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 33, "clsize" => "15", "clheader" => "Identificação", "clname" => "tpfnidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 4, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 33, 'clsize' => '15', 
        'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 13, 'clorder' => 50, 'clvisible' => 1, 'clstatus' => 1, 
        'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        ColumnCal::create(["fkidcal" => 40, "clsize" => "7", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 40, "clsize" => "30", "clheader" => "Identificação", "clname" => "gidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 40, "clsize" => "5", "clheader" => "Status", "clname" => "gstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 3, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 40, "clsize" => "20", "clheader" => "Anotação", "clname" => "ganotation", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 40, "clsize" => "5", "clheader" => "Registro", "clname" => "gversao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 3, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 40, "clsize" => "5", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 43, "clsize" => "30", "clheader" => "Identificação", "clname" => "tpctidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 7, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 43, "clsize" => "30", "clheader" => "Identificação Plural", "clname" => "tpctidentificacaoplural", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 14, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 43, "clsize" => "5", "clheader" => "Status", "clname" => "tpctstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 43, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Classe Social", "clname" => "clscidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Profissão", "clname" => "pfidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Estado Civil", "clname" => "ecidentificacao1", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Tratamento", "clname" => "ttidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Escolaridade", "clname" => "ecidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Ramo de Atividade", "clname" => "rtidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Cidade", "clname" => "cdidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Tipo Sanguíneo", "clname" => "untiposanguineo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Escolaridade", "clname" => "fkidescolaridade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Ramo Atividade", "clname" => "fkidramoatividade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Profissão", "clname" => "fkidprofissao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Classe Social", "clname" => "fkidclassesocial", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "CNPJ", "clname" => "uncnpj", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Seção Eleitoral", "clname" => "unsecaoeleitoral", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Zona Eleitoral", "clname" => "unzonaeleitoral", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Pis", "clname" => "unpis", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Num. Cart. Trabalho", "clname" => "unnumcarttrabalho", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "CEP", "clname" => "uncep", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Nome Fantasia", "clname" => "unnomefantasia", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "CPF", "clname" => "uncpf", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "RG", "clname" => "unrg", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Data Nasc.", "clname" => "undatanasc", "clalinhamento" => "left", "cltipocampo" => 2, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Data Cadastro", "clname" => "undatacadastro", "clalinhamento" => "left", "cltipocampo" => 2, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Série", "clname" => "unserie", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 0, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Insc. Munic.", "clname" => "uninscrmunicipal", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Tratamento", "clname" => "fkidtratamento", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Estado Civil", "clname" => "fkidestadocivil", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Cidade", "clname" => "fkidcidade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Raça", "clname" => "fkidraca", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Data", "clname" => "unversao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Obs.", "clname" => "unobs", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Insc. Estadual", "clname" => "uninscrestadual", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Designação", "clname" => "undesignacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Sexo", "clname" => "unsexo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Complemento", "clname" => "uncomplemento", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Número", "clname" => "unnumero", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Bairro", "clname" => "unbairro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Endereço", "clname" => "unendereco", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Opta Simples", "clname" => "unoptasimples", "clalinhamento" => "left", "cltipocampo" => 5, "clorder" => 50, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "2", "clheader" => "Visibilidade", "clname" => "unstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 70, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "2", "clheader" => "", "clname" => "avatar", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 8, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "30", "clheader" => "Identificação", "clname" => "unidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "15", "clheader" => "Tipo de Cadastro", "clname" => "tpcidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 9, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "20", "clheader" => "Dados", "clname" => "unapelido", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 51, "clsize" => "20", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 18, "clorder" => 80, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 52, "clsize" => "7", "clheader" => "Tipo Logradouro", "clname" => "endtipologradouro", "clalinhamento" => "left", "cltipocampo" => 15, "clorder" => 5, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "4", "clheader" => "Cep", "clname" => "endcep", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 7, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "7", "clheader" => "Bairro", "clname" => "endbairro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 7, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "3", "clheader" => "Status", "clname" => "endstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 9, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "6", "clheader" => "Cidade", "clname" => "cidade", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "15", "clheader" => "Logradouro", "clname" => "endlogradouro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "15", "clheader" => "Bairro", "clname" => "endbairro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "15", "clheader" => "Cód", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 4, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 52, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 54, "clsize" => "2", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "20", "clheader" => "Identificação", "clname" => "identificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 43, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Tipo", "clname" => "tipodado", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 44, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Status", "clname" => "status", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 48, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Classific.", "clname" => "classificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 44, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Iní­cio", "clname" => "valor1", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 44, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Fim", "clname" => "valor2", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 44, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "7", "clheader" => "Data Registro", "clname" => "versao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 44, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 54, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 55, "clsize" => "15", "clheader" => "Identificação", "clname" => "pridentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 3, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 56, "clsize" => "20", "clheader" => "Identificação", "clname" => "undidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 56, "clsize" => "20", "clheader" => "Dados", "clname" => "unddatacadastro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 56, "clsize" => "20", "clheader" => "Inform.", "clname" => "uncnpj", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 40, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 56, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 57, "clsize" => "15", "clheader" => "Identificação", "clname" => "ridentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 57, "clsize" => "35", "clheader" => "Conteúdo", "clname" => "rtexto", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 57, "clsize" => "20", "clheader" => "Dados", "clname" => "rdatahora", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 57, 'clsize' => '10', 'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 16, 'clorder' => 200, 'clvisible' => 1, 'clstatus' => 1, 'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
    
        
        ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "Valor de Final", "clname" => "valor2", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 80, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "30", "clheader" => "Identificação", "clname" => "identificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "Tipo", "clname" => "tipodado", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 12, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "Status", "clname" => "status", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 5, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "7", "clheader" => "Data Registro", "clname" => "versao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 90, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "Classificação", "clname" => "classificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "15", "clheader" => "Valor de Inicial", "clname" => "valor1", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 70, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 58, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 100, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 59, "clsize" => "1", "clheader" => "Login", "clname" => "ulogin", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 59, "clsize" => "15", "clheader" => "Usuário", "clname" => "unidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 59, "clsize" => "15", "clheader" => "Status", "clname" => "status", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 4, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        
        ColumnCal::create(["fkidcal" => 62, "clsize" => "15", "clheader" => "Identificação", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "7", "clheader" => "Rótulo", "clname" => "scdestaque", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 62, "clsize" => "30", "clheader" => "Conteúdo", "clname" => "scementa", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 3, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "7", "clheader" => "Abrir em", "clname" => "scabrirem", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 3, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "7", "clheader" => "O que Abrir", "clname" => "scoqueabrir", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 4, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "5", "clheader" => "Ativo", "clname" => "scstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 5, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "7", "clheader" => "Categoria", "clname" => "ccidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 1, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "4", "clheader" => "Visibilidade", "clname" => "scvisibilidade", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 8, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "4", "clheader" => "Link", "clname" => "sclink", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 9, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "3", "clheader" => "Início", "clname" => "scperiodovisivelinicio", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "5", "clheader" => "Final", "clname" => "scperiodovisivelfinal", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 11, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        //ColumnCal::create(["fkidcal" => 62, "clsize" => "4", "clheader" => "Tags", "clname" => "sctags", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 12, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(['fkidcal' => 62, 'clsize' => '10', 'clheader' => '#', 'clname' => 'acao', 'clalinhamento' => 'left', 'cltipocampo' => 17, 'clorder' => 200, 'clvisible' => 1, 'clstatus' => 1, 'clversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
    
        ColumnCal::create(["fkidcal" => 66, "clsize" => "5", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "20", "clheader" => "Onde", "clname" => "lgonde", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "5", "clheader" => "Tipo Ação", "clname" => "fktipoacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "5", "clheader" => "Usuário", "clname" => "fkidusuario", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "5", "clheader" => "Id Registro", "clname" => "idregistro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 40, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "20", "clheader" => "Texto", "clname" => "lgtexto", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 45, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 66, "clsize" => "5", "clheader" => "Data", "clname" => "lgversao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);

        ColumnCal::create(["fkidcal" => 68, "clsize" => "15", "clheader" => "Identificação", "clname" => "pfidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 68, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Identificação", "clname" => "rtidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Versão", "clname" => "rtcnaeversao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Divisão", "clname" => "rtcnaedivisao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 22, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Classe", "clname" => "rtcnaeclasse", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Grupo", "clname" => "rtcnaegrupo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "Seção", "clname" => "rtcnaesecao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 35, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "20", "clheader" => "SubClasse", "clname" => "rtcnaesubclasse", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 40, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 69, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        ColumnCal::create(["fkidcal" => 70, "clsize" => "15", "clheader" => "Identificação", "clname" => "ecidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 70, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        
        
        ColumnCal::create(["fkidcal" => 100, "clsize" => "15", "clheader" => "Identificação", "clname" => "tpaidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 100, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);

    
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Cód", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 2, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Identif.", "clname" => "mnidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 4, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.2", "clheader" => "Versão", "clname" => "mnversao", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Menu pai", "clname" => "identmenupai", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Cal", "clname" => "clidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Ordem", "clname" => "mnsequencia", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 18, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.2", "clheader" => "Situação", "clname" => "mnstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "Numeração", "clname" => "mnnumeracao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 5, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 124, "clsize" => "0.5", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
       

        ColumnCal::create(["fkidcal" => 131, "clsize" => "1", "clheader" => "Cod", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 131, "clsize" => "10", "clheader" => "Identificação", "clname" => "cidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 131, "clsize" => "20", "clheader" => "Autorizados", "clname" => "membros", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 28, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 131, "clsize" => "0.5", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);

        ColumnCal::create(["fkidcal" => 132, "clsize" => "1", "clheader" => "Num", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 132, "clsize" => "15", "clheader" => "Identificação", "clname" => "adidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 132, "clsize" => "15", "clheader" => "Dados", "clname" => "addatacadastro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 28, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 132, "clsize" => "20", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
     
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "Identificação", "clname" => "pidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "Unid. Medida", "clname" => "punidademedida", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 33, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "Estoque Atual", "clname" => "pqtdatual", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 29, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "Estoque Mínimo", "clname" => "plimiteestoqueminimo", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 32, "clvisible" => 0, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "Dados", "clname" => "pobs", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 35, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 135, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 16, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);

        ColumnCal::create(["fkidcal" => 152, "clsize" => "15", "clheader" => "Identificação", "clname" => "cidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 152, "clsize" => "5", "clheader" => "Status", "clname" => "cstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 20, "clvisible" => 0, "clstatus" => 0, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 152, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);


        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "Nome", "clname" => "unidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "Fone", "clname" => "fone", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "Dados", "clname" => "unbairro", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "E-mail", "clname" => "email", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "Perfil", "clname" => "avatar", "clalinhamento" => "left", "cltipocampo" => 14, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 145, "clsize" => "15", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        

        ColumnCal::create(["fkidcal" => 193, "clsize" => "25", "clheader" => "Identificação", "clname" => "tpaidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 193, "clsize" => "25", "clheader" => "Identificação Plural", "clname" => "tpaplural", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 193, "clsize" => "25", "clheader" => "Classificação", "clname" => "tpaclassificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 193, "clsize" => "10", "clheader" => "Status", "clname" => "tpastatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 193, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);

        ColumnCal::create(["fkidcal" => 194, "clsize" => "50", "clheader" => "Identificação", "clname" => "tpidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 194, "clsize" => "10", "clheader" => "Status", "clname" => "tpstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 194, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
       
        ColumnCal::create(["fkidcal" => 196, "clsize" => "50", "clheader" => "Identificação", "clname" => "tpetidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 15, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 196, "clsize" => "10", "clheader" => "Status", "clname" => "tpetstatus", "clalinhamento" => "left", "cltipocampo" => 4, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 196, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 13, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
       

        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "ID", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 10, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Tipo Usuário", "clname" => "user_type", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "ID Usuário", "clname" => "user_id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Evento", "clname" => "event", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 30, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Tabela", "clname" => "auditable_type", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 40, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Id Reg", "clname" => "auditable_id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 45, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "20", "clheader" => "Valores Antigos", "clname" => "old_values", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "20", "clheader" => "Novo Valor", "clname" => "new_values", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 55, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Local", "clname" => "url", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 60, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "IP", "clname" => "ip_address", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 65, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Agente", "clname" => "user_agent", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 70, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "2", "clheader" => "Tag", "clname" => "tags", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 75, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Criado Em", "clname" => "created_at", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 80, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 197, "clsize" => "5", "clheader" => "Atualiza", "clname" => "updated_at", "clalinhamento" => "left", "cltipocampo" => 3, "clorder" => 85, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flaguser" => 1, "fkidgestor" => $fkidgestorparam]);

        ColumnCal::create(["fkidcal" => 201, "clsize" => "1", "clheader" => "Num", "clname" => "id", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 20, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 201, "clsize" => "35", "clheader" => "Identificação", "clname" => "maidentificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 25, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 201, "clsize" => "25", "clheader" => "Classificação", "clname" => "classificacao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 28, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 201, "clsize" => "10", "clheader" => "Dados", "clname" => "maversao", "clalinhamento" => "left", "cltipocampo" => 1, "clorder" => 33, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);
        ColumnCal::create(["fkidcal" => 201, "clsize" => "10", "clheader" => "#", "clname" => "acao", "clalinhamento" => "left", "cltipocampo" => 16, "clorder" => 50, "clvisible" => 1, "clstatus" => 1, "clversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flaguser" => 0, "fkidgestor" => $fkidgestorparam]);

        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

    }
}
 