<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.  php artisan db:seed --class=MenuSeeder
     *
     * @return void
     */
    public function run()
    {
        Menu::truncate();
        
        Menu::create(["id" => 10001, "mnidentificacao" => "Início", "mnnumeracao" => "01", "mnicone" => "fas fa-bookmark", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 0, "fkidcal" => 64, "mnsequencia" => 10001, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flagcontrole" => 1, "flaguser" => 1]);

        Menu::create(["id" => 12000, "mnidentificacao" => "Portal", "mnnumeracao" => "10", "mnicone" => "fas fa-adjust", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 0, "fkidcal" => 62, "mnsequencia" => 12000, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 12001, "mnidentificacao" => "Conteúdo do Site", "mnnumeracao" => "10.1", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 12000, "fkidcal" => 62, "mnsequencia" => 12001, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        
        Menu::create(["id" => 14004, "mnidentificacao" => "Administrativos", "mnnumeracao" => "30.3", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 14001, "fkidcal" => 9, "mnsequencia" => 14004, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 14006, "mnidentificacao" => "Correspondências", "mnnumeracao" => "30.5", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 14001, "fkidcal" => 10, "mnsequencia" => 14006, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 14007, "mnidentificacao" => "Diversos", "mnnumeracao" => "30.6", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 14001, "fkidcal" => 8, "mnsequencia" => 14007, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 14008, "mnidentificacao" => "Reuniões/Atas", "mnnumeracao" => "30.7", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 14001, "fkidcal" => 57, "mnsequencia" => 14008, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        
        Menu::create(["id" => 18001, "mnidentificacao" => "Controle", "mnnumeracao" => "70", "mnicone" => "fa fa-cog", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 0, "fkidcal" => 199, "mnsequencia" => 18001, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18002, "mnidentificacao" => "Cals Sistema", "mnnumeracao" => "70.1", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 28, "mnsequencia" => 18002, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18003, "mnidentificacao" => "Controle Acesso", "mnnumeracao" => "70.2", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 40, "mnsequencia" => 18003, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18005, "mnidentificacao" => "Conf. Sistema", "mnnumeracao" => "70.4", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 54, "mnsequencia" => 18005, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18008, "mnidentificacao" => "Menus", "mnnumeracao" => "70.7", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 124, "mnsequencia" => 18008, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18009, "mnidentificacao" => "Auditoria Sistema", "mnnumeracao" => "70.8", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 197, "mnsequencia" => 18009, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18010, "mnidentificacao" => "Logs Sistema", "mnnumeracao" => "70.9", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 66, "mnsequencia" => 18010, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18011, "mnidentificacao" => "Certificados", "mnnumeracao" => "70.10", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 131, "mnsequencia" => 18011, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18012, "mnidentificacao" => "Assinatura Digital", "mnnumeracao" => "70.11", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 132, "mnsequencia" => 18012, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18016, "mnidentificacao" => "Estoque", "mnnumeracao" => "70.15", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 135, "mnsequencia" => 18016, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 18017, "mnidentificacao" => "Carteira Funcional", "mnnumeracao" => "70.16", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 18001, "fkidcal" => 134, "mnsequencia" => 18017, "mnstatus" => 0, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 1, "flagcontrole" => 1, "flaguser" => 1]);


        
        Menu::create(["id" => 19001, "mnidentificacao" => "Cadastros", "mnnumeracao" => "80", "mnicone" => "fas fa-dot-circle", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 0, "fkidcal" => 198, "mnsequencia" => 19001, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19002, "mnidentificacao" => "Cadastro Unificado", "mnnumeracao" => "80.1", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 51, "mnsequencia" => 19007, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19004, "mnidentificacao" => "Cadastro Unidades", "mnnumeracao" => "80.3", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 56, "mnsequencia" => 19013, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19014, "mnidentificacao" => "Eventos", "mnnumeracao" => "80.4", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 184, "mnsequencia" => 19016, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19005, "mnidentificacao" => "Funcionários", "mnnumeracao" => "80.5", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 21, "mnsequencia" => 19020, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19006, "mnidentificacao" => "Divisões", "mnnumeracao" => "80.8", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 19, "mnsequencia" => 19023, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 19016, "mnidentificacao" => "Meus Dados", "mnnumeracao" => "80.10", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 19001, "fkidcal" => 204, "mnsequencia" => 19058, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        

    
        Menu::create(["id" => 20004, "mnidentificacao" => "Tipos Alterações", "mnnumeracao" => "90.3", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 100, "mnsequencia" => 20004, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20005, "mnidentificacao" => "Tipos Parentescos", "mnnumeracao" => "90.4", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 194, "mnsequencia" => 20005, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20017, "mnidentificacao" => "Tipos Categorias", "mnnumeracao" => "90.16", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 43, "mnsequencia" => 20017, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20032, "mnidentificacao" => "Categorias", "mnnumeracao" => "90.17", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 152, "mnsequencia" => 20017, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20018, "mnidentificacao" => "Estados Civis", "mnnumeracao" => "90.18", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 20, "mnsequencia" => 20018, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20019, "mnidentificacao" => "Classes Sociais", "mnnumeracao" => "90.19", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 15, "mnsequencia" => 20019, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20020, "mnidentificacao" => "Tratamentos", "mnnumeracao" => "90.20", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 29, "mnsequencia" => 20020, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20021, "mnidentificacao" => "Cidades", "mnnumeracao" => "90.21", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 17, "mnsequencia" => 20021, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20022, "mnidentificacao" => "Profissões", "mnnumeracao" => "90.22", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 68, "mnsequencia" => 20022, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20023, "mnidentificacao" => "Ramos de Atividades", "mnnumeracao" => "90.23", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 69, "mnsequencia" => 20023, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20024, "mnidentificacao" => "Escolaridades", "mnnumeracao" => "90.24", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 70, "mnsequencia" => 20024, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20025, "mnidentificacao" => "Endereços", "mnnumeracao" => "90.25", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 52, "mnsequencia" => 20025, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);        
        Menu::create(["id" => 20028, "mnidentificacao" => "Tipos Arquivos", "mnnumeracao" => "90.28", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 193, "mnsequencia" => 20028, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20029, "mnidentificacao" => "Tipos Etapas", "mnnumeracao" => "90.29", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 196, "mnsequencia" => 20029, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20031, "mnidentificacao" => "Cargos", "mnnumeracao" => "90.31", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 16, "mnsequencia" => 20031, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(["id" => 20033, "mnidentificacao" => "Modelos Documentos", "mnnumeracao" => "90.32", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 20001, "fkidcal" => 201, "mnsequencia" => 20031, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);

        Menu::create(['id' => 30001, 'mnidentificacao' => 'Ajuda', 'mnnumeracao' => '99', 'mnicone' => 'fas fa-info-circle', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 0, 'fkidcal' => 65, 'mnsequencia' => 30001, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(["id" => 30002, "mnidentificacao" => "O que há de novo", "mnnumeracao" => "99.1", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 30001, "fkidcal" => 0, "mnsequencia" => 30002, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(['id' => 30003, 'mnidentificacao' => 'Sobre', 'mnnumeracao' => '99.1', 'mnicone' => '', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 65, 'mnsequencia' => 30003, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(["id" => 30004, "mnidentificacao" => "Sobre", "mnnumeracao" => "99.2", "mnicone" => "", "mndestaque" => "", "mnskin" => "", "fkidmenunivelacima" => 30001, "fkidcal" => 0, "mnsequencia" => 30004, "mnstatus" => 1, "mnversao" => Carbon::now()->toDateTimeString(), "flagdelete" => 0, "flagatualiza" => 0, "flagcontrole" => 1, "flaguser" => 0]);
        Menu::create(['id' => 30005, 'mnidentificacao' => 'Termos de Uso', 'mnnumeracao' => '99.2', 'mnicone' => '', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 141, 'mnsequencia' => 30005, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(['id' => 30006, 'mnidentificacao' => 'Versões', 'mnnumeracao' => '99.3', 'mnicone' => '', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 142, 'mnsequencia' => 30006, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(['id' => 30007, 'mnidentificacao' => 'Reportar Problema', 'mnnumeracao' => '99.4', 'mnicone' => '', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 143, 'mnsequencia' => 30007, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(['id' => 30008, 'mnidentificacao' => 'Contato', 'mnnumeracao' => '99.5', 'mnicone' => '', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 144, 'mnsequencia' => 30008, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);
        Menu::create(['id' => 30009, 'mnidentificacao' => 'Aprender', 'mnnumeracao' => '99.6', 'mnicone' => 'fab fa-youtube', 'mndestaque' => '', 'mnskin' => '', 'fkidmenunivelacima' => 30001, 'fkidcal' => 176, 'mnsequencia' => 30009, 'mnstatus' => 1, 'mnversao' => Carbon::now()->toDateTimeString(), 'flagdelete' => 0, 'flagatualiza' => 1, 'flagcontrole' => 1, 'flaguser' => 0]);


    }
}

